POST http://localhost:8080/api/todos
Accept: application/json
Content-Type: application/json

{
  "title": "Poznać Rusta",
  "description": "Trudna sprawa"
}

###

GET http://localhost:8080/api/todos/b60ce5be-ff1a-41a5-8867-3483559054f4
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/todos?completed=false
Accept: application/json
Content-Type: application/json
